# Generated by Django 3.2.3 on 2021-07-06 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAMES', models.CharField(max_length=50, unique=True)),
                ('EMPLOYEE_ID', models.CharField(max_length=4, unique=True)),
                ('MANAGER_ID', models.CharField(max_length=4, null=True)),
                ('MANAGEMENT_LEVEL', models.CharField(max_length=20)),
                ('DESIGNATION', models.CharField(max_length=20)),
                ('STAFF', models.CharField(max_length=7)),
                ('EMPLOYEE_STATUS', models.CharField(max_length=20)),
                ('PROCESS', models.CharField(max_length=20)),
                ('DEPARTMENT', models.CharField(max_length=15)),
                ('TYPE_OF_SALARY', models.CharField(max_length=30)),
                ('SALARY', models.IntegerField()),
                ('DATE_OF_BIRTH', models.DateField()),
                ('LOCATION_ID', models.CharField(max_length=10, null=True)),
                ('PHONE_NUMBER', models.IntegerField()),
                ('HIRE_DATE', models.DateField()),
                ('END_DATE', models.DateField(null=True)),
                ('DEPARTMENT_ID', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='loginpage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=30)),
                ('Emp_ID', models.CharField(blank=True, max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfileInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('email', models.EmailField(max_length=60, unique=True)),
                ('confirm_email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=30)),
                ('confirm_password', models.CharField(max_length=30)),
                ('birth_date', models.DateField()),
                ('First_Name', models.CharField(max_length=30)),
                ('Last_Name', models.CharField(max_length=30)),
                ('Emp_ID', models.CharField(max_length=6, unique=True)),
            ],
        ),
    ]
